### PR TITLE
test: fix findOneAndUpdate to return new data

### PR DESCRIPTION
**Pull request by Fonger**
mongoose breaking changes in v4: findOneAndUpdate will return old data by default
https://github.com/Automattic/mongoose/commit/8b31481ce665141b47d689b71fc10565b056c43b

### CODE REVIEW

**Comment by Fonger** [comment]
I'm not sure why the test still failed

**Comment by vkarpov15** [comment]
@Fonger which test specifically?

**Comment by Fonger** [comment]
> @Fonger which test specifically?

It passes on my local machine but fails on semaphore CI
https://semaphoreci.com/vkarpov15/mongoose-lean-id/branches/master/builds/16

**Comment by vkarpov15** [comment]
Weird, might be something wrong with the semaphore integration. Not a big deal for now.

**Pull request merged**
